services:
  db:
    image: mysql:8.0
    container_name: silver_empire_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME:-silver_empire}
      MYSQL_USER: ${DB_USER:-silverempire}
      MYSQL_PASSWORD: ${DB_PASSWORD:-silverpass123}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass123}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - silver_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    container_name: silver_empire_web
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production}
      - DB_NAME=${DB_NAME:-silver_empire}
      - DB_USER=${DB_USER:-silverempire}
      - DB_PASSWORD=${DB_PASSWORD:-silverpass123}
      - DB_HOST=db
      - DB_PORT=3306
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL:-admin@silverempire.com}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD:-admin123}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - silver_network

  nginx:
    image: nginx:alpine
    container_name: silver_empire_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - silver_network

volumes:
  mysql_data:
  static_volume:
  media_volume:

networks:
  silver_network:
    driver: bridge