version: "3.8"

services:
  backend:
    build: .
    container_name: silver_empire_backend
    network_mode: "host"
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production}
      - DB_NAME=${DB_NAME:-silver_empire}
      - DB_USER=${DB_USER:-silverempire}
      - DB_PASSWORD=${DB_PASSWORD:-silverpass123}
      - DB_HOST=${DB_HOST:-127.0.0.1}  # point to your local MySQL
      - DB_PORT=${DB_PORT:-3306}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL:-admin@silverempire.com}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD:-admin123}
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - silver_network

volumes:
  static_volume:
  media_volume:

networks:
  silver_network:
    driver: bridge