# Generated by Django 5.2.7 on 2025-10-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_shipping_address_order_shipping_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="shipping_postal_code",
            new_name="shipping_zip_code",
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_state",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
